---
- name: "Automate Docker Build using Ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop survey-cont
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm survey-cont
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi survey-img
    ignore_errors: yes
    
  - name: build docker image from dockerfile
    command: docker build -t survey-img .  

  - name: run container from image
    command: docker run -d --name survey-cont -p 4000:8000 survey-img