---
- name: "Automate deploying containers with ansible playbook on the cluster"
  hosts: localhost

  vars_files:
    - vars.yml

  tasks:

  - name: remove previous build
    shell: docker rmi -f $(docker images -q {{ USER_NAME }}/{{ REPO_NAME }})
    ignore_errors: yes

  - name: build a new docker image
    command: docker build -t {{ USER_NAME }}/{{ REPO_NAME }}:{{ IMAGE_TAG }} .

  - name: push docker image to dockerhub
    command: docker push {{ USER_NAME }}/{{ REPO_NAME }}:{{ IMAGE_TAG }}

  - name: create namespace if not exist
    command: kubectl create namespace {{ NAMESPACE }}
    ignore_errors: yes

  - name: deploy the app
    command: kubectl apply -f ./k8s
