---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi comingsoon-image
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t comingsoon-image .

    - name: run container
      command: docker run -d --name web-container -p 5000:80 comingsoon-image

